name: Deploy

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy branch'

jobs:
  build_front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - name: get front
      uses: actions/checkout@v2
      with:
        repository: 'frontend-park-mail-ru/2020_2_softree'
        ref: ${{ github.event.inputs.tags }}

    - name: use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: get dependecies
      run: npm ci

    - name: build
      run: npm run build

    - name: upload build result
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist

  deploy_front:
    runs-on: ubuntu-latest
    needs: build_front
    steps:
    - name: Checkout dir
      uses: actions/checkout@v2

    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: upload to hotbox
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_S3_ENDPOINT:  https://storage.yandexcloud.net
        AWS_REGION: 'ru-central1'
        SOURCE_DIR: 'dist'

  deploy_back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dir
        uses: actions/checkout@v2

      - name: deploy backend
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            ---
            all:
              hosts:
                prod-servers:
                  ansible_host: '178.154.227.8'
                  ansible_user: 'root'
                  ansible_python_interpreter: '/usr/bin/python3'

          vault_password: ${{secrets.VAULT_PASSWORD}}
